version: "3.8"

services:
  # Landing Page Service
  landing:
    image: novn01/konsul-pajak-landing:latest
    container_name: konsul_pajak_landing
    environment:
      - PORT=3000
      - NODE_ENV=production
    networks:
      - proxy
    expose:
      - "3000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.konsul_landing.rule=Host(`landing.novn.my.id`)"
      - "traefik.http.routers.konsul_landing.entrypoints=websecure"
      - "traefik.http.routers.konsul_landing.tls=true"
      - "traefik.http.routers.konsul_landing.tls.certresolver=letsencrypt"
      - "traefik.http.services.konsul_landing.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

  # Chat Application Service
  chat:
    image: novn01/konsul-pajak-chat:latest
    container_name: konsul_pajak_chat
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
    networks:
      - proxy
    expose:
      - "3000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.konsul_chat.rule=Host(`chat.novn.my.id`)"
      - "traefik.http.routers.konsul_chat.entrypoints=websecure"
      - "traefik.http.routers.konsul_chat.tls=true"
      - "traefik.http.routers.konsul_chat.tls.certresolver=letsencrypt"
      - "traefik.http.services.konsul_chat.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
    name: proxy
